### ISSUE TITLE
Add force-default method

### ISSUE THREAD

**Issue by dpi** [forxer/gravatar#2]
A force default method should be added to Image class which should set `f` or `forcedefault` query param to 'y'

Per https://en.gravatar.com/site/implement/images/

> If for some reason you wanted to force the default image to always load, you can do that by using the f= or forcedefault= parameter, and setting its value to y.

**Comment by forxer** [comment]
Support added in 1.3.0 with a seventh parameter of the main Gravater class. And with enableForceDefault(), disableForceDefault() and forcingDefault() methods of the image class.
