### ISSUE TITLE
How to let users upload a gravatar

### ISSUE THREAD

**Issue by elieobeid7** [forxer/gravatar#4]
How to let users upload a gravatar or change their existing one?

**Comment by forxer** [comment]
Hello, 

Using the [Gravatar ](https://gravatar.com/) service :)

**Comment by elieobeid7** [comment]
I mean using php anyhow forget it I'm doing what stackoverflow did, if a user don't want his avatar I'm gonna let him upload a picture

**Comment by forxer** [comment]
I do not know what Stackoverflow does, but from what I understand, this is to be managed on your side, it is not the purpose of this package. This library only serves to easily generate Gravatar URLs.
